### PR TITLE
[1.16] performance: run network updates in parallel where possible

### PR DESCRIPTION
**Pull request by Geo25rey**
See discussion: #1152

### CODE REVIEW

**Review by rubensworks — CHANGES_REQUESTED** [review]
Parallelizing these `IFullNetworkListener`'s will unfortunately break things, because their implementations are not thread-safe (because MC's world-interactions are not thread-safe).

Furthermore, there are only 2 implementations of `IFullNetworkListener` (`PartNetwork` and `EnergyNetwork`), so the impact of parallelizing will be minimal I suspect. Unless you have proof otherwise?

**Comment by Geo25rey** [comment]
> the impact of parallelizing will be minimal I suspect. Unless you have proof otherwise?

No proof otherwise haha, that bit was a more theoretical patch. I intended to test it, but again I couldn't get it to build locally.

**Comment by rubensworks** [comment]
> but again I couldn't get it to build locally.

I suspect you're having issues with the GitHub dependencies?
If so, this guide may help: https://github.com/CyclopsMC/IntegratedDynamics/wiki/Addon-Development%3A-Getting-Started#using-a-latest-development-version

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/IntegratedDynamics">Addon Development: Getting Started · CyclopsMC/IntegratedDynamics Wiki</a></strong></div><div>A Minecraft mod to take full and automated control of your appliances. - Addon Development: Getting Started · CyclopsMC/IntegratedDynamics Wiki</div></blockquote>

Edit: I should really update the README with these details at some point...

**Comment by rubensworks** [comment]
Closing due to inactivity.

**Pull request closed without merging**
