### PR TITLE
Initial Implementation for String Parse

### PR DESCRIPTION
**Pull request by LostOfThought**
Functional, but really just a big cast clone....

Ref: #690

### CODE REVIEW

**Comment by rubensworks** [comment]
I haven't looked in detail into this yet, but a couple of things I notice atm:

* Parsing only really makes sense from string to something else. So I would remove the handlers for the reverse way. (And refactor so that the input is always a string)
* All ID operators are extensively unit tested, so this would also need unit tests.

**Comment by LostOfThought** [comment]
Renamed to a more generic 'StringConversion'
OP name is dependant on direction (`<type>_as_String`/`parse_<type>`)

I'll get around to unit tests (possab|eventual)ly.

**Comment by rubensworks** [comment]
`<type>_as_String` should not really be needed. You can already convert anything to string using the `name`(or something like that) operator AFAIK.

**Comment by LostOfThought** [comment]
`name` fails for NBT

**Comment by rubensworks** [comment]
> `name` fails for NBT

Sounds like a bug then :-)

**Comment by LostOfThought** [comment]
Not too much more to go.
Let me know if you see any more glaring issues.

**Comment by LostOfThought** [comment]
And yes, spam copy/paste tests lead to several wrong assertion texts.

**Comment by rubensworks** [comment]
I don't see any major issues atm. Will review in detail once the unit tests pass.

**Pull request closed without merging**
