### PR TITLE
Convert Operators to lambdas

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by rubensworks** [comment]
So this doesn't convert all operators yet?
Shall I leave this PR open until all of them have been converted?

**Comment by josephcsible** [comment]
It's up to you. If you'd rather only have one PR, you can leave it, otherwise go ahead and merge it and I'll make a new one for the second half.

**Comment by rubensworks** [comment]
I feel it's better to have these changes limited to one commit, so I'll leave this PR open.

**Comment by josephcsible** [comment]
The second half of this is done now, so it's ready to merge. The only ones I didn't do are self-referential in a way that makes them not allowed to be lambdas.

**Comment by rubensworks** [comment]
This one also has merge conflicts now because of #396.

**Comment by josephcsible** [comment]
Resolved.

**Pull request merged**
