### PR TITLE
Losslessly compress all of the PNGs

### PR DESCRIPTION
**Pull request by josephcsible**
Old size: 1,037,634 bytes
New size: 173,564 bytes (17%)
Savings: 864,070 bytes (83%)

### CODE REVIEW

**Comment by josephcsible** [comment]
Note that I ran into https://bugs.mojang.com/browse/MC-12699 on some of these files the first time I tried this. I think I fixed all of them, but I'm not 100% sure.

**Comment by rubensworks** [comment]
Oh, that's quite significant! That will definitely reduce the jar size.

What tool did you use for compression? I'll make sure to use it in the future as well.

**Comment by josephcsible** [comment]
I used zopflipng from https://github.com/google/zopfli. Here's what I had to change in it to work around MC-12699:
```diff
diff --git a/src/zopflipng/lodepng/lodepng.cpp b/src/zopflipng/lodepng/lodepng.cpp
index 59e3af9..9c24808 100644
--- a/src/zopflipng/lodepng/lodepng.cpp
+++ b/src/zopflipng/lodepng/lodepng.cpp
@@ -3749,7 +3749,7 @@ unsigned lodepng_auto_choose_color(LodePNGColorMode* mode_out,
   if(error) return error;
   mode_out->key_defined = 0;
 
-  if(prof.key && w * h <= 16)
+  if(prof.key /*&& w * h <= 16*/)
   {
     prof.alpha = 1; /*too few pixels to justify tRNS chunk overhead*/
     if(prof.bits < 8) prof.bits = 8; /*PNG has no alphachannel modes with less than 8-bit per channel*/
diff --git a/src/zopflipng/zopflipng_lib.cc b/src/zopflipng/zopflipng_lib.cc
index b93bb18..00ee37d 100644
--- a/src/zopflipng/zopflipng_lib.cc
+++ b/src/zopflipng/zopflipng_lib.cc
@@ -237,7 +237,7 @@ unsigned TryOptimize(
       lodepng_color_profile_init(&profile);
       lodepng_get_color_profile(&profile, &image[0], w, h, &state.info_raw);
       // Too small for tRNS chunk overhead.
-      if (w * h <= 16 && profile.key) profile.alpha = 1;
+      if (/*w * h <= 16 &&*/ profile.key) profile.alpha = 1;
       state.encoder.auto_convert = 0;
       state.info_png.color.colortype = (profile.alpha ? LCT_RGBA : LCT_RGB);
       state.info_png.color.bitdepth = 8;

```

**Comment by rubensworks** [comment]
Neat! Will look into it, thanks :-)

**Comment by rubensworks** [comment]
The final jar has been reduced in size from 3.2 MB to 2.4 MB, awesome!

**Comment by rubensworks** [comment]
@josephcsible What arguments did you use to perform the compression?

From a quick test my input file seems to be sufficiently compressed with the default settings, with the "optimized" parameters it takes a lot longer, and doesn't result in a significantly smaller file.

Fyi, I've forked zopfli here: https://github.com/CyclopsMC/zopfli
In case later changes to it would be needed later on.

**Comment by josephcsible** [comment]
I used "-m --filters=01234mep".

**Pull request merged**
