### PR TITLE
Clear facade recipes

### LINKED ISSUE #1424: Recipe for resetting facade texture
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

As the title described. For now after a facade has crafted with another block and turns into its texture, there's no way for the facade to return to its original no-texture form. This feature will be useful for storing disassembled facades. Such recipe might be as simple as putting a single facade into the crafting grid.

### PR DESCRIPTION
**Pull request by kirjorjos**
Closes #1424 by adding a normal crafting recipe for lossy clearing and a recipe in both squeezers for non-lossy clearing

### CODE REVIEW

**Review by rubensworks — CHANGES_REQUESTED** [review]
I understand the need for a custom recipe serializer, but I'm pretty sure the custom recipe type is not necessary. Could you try using the existing recipe type? I think this will simplify this code by a lot.

**Comment by kirjorjos** [comment]
I could modify the 2 existing recipe types to directly call the calculator method, but the reason I did it with an additional recipe type is to make it clear in the JSON recipe files that it's a special type.  If you think that just putting it in the special folder twice won't cause too much confusion, I'll go ahead and modify the 2 existing classes to directly call the calculator method.

**Comment by rubensworks** [comment]
Sure, modifying the existing recipe type is fine. It would become a bit similar to the crafting recipe type, so we can probably even use the same method name as there.

**Comment by kirjorjos** [comment]
I'm closing this PR to open a new one on a new branch to both keep the commit history cleaner and help me make sure I don't forget to delete any unrequired code.

**Pull request closed without merging**
