### PR TITLE
Change FE to Energy

### PR DESCRIPTION
**Pull request by TomyLobo**
This gets the name and info of the operators for items in line with the corresponding operators for entities.

### CODE REVIEW

**Comment by TomyLobo** [comment]
I'd love to sign the CLA, but why does that CLA assistant need my email address? sounds fishy...

**Review by rubensworks — CHANGES_REQUESTED** [review]
I'm fine with this change, but I would consistently replace all FE occurences then, as there seem to be some more usages in the aspect entries.

**Comment by rubensworks** [comment]
> I'd love to sign the CLA, but why does that CLA assistant need my email address? sounds fishy...

@TomyLobo That's just how the CLA assistant handles user identification. I can't merge without it unfortunately.

**Comment by TomyLobo** [comment]
> I'm fine with this change, but I would consistently replace all FE occurences then, as there seem to be some more usages in the aspect entries.

Hmm, I haven't used those, I don't want to change things where I don't know what they do.
Btw, I signed the CLA.

**Comment by rubensworks** [comment]
> Hmm, I haven't used those, I don't want to change things where I don't know what they do.

They are in the same document. A simple `FE` grep will show their location.

**Comment by TomyLobo** [comment]
I know, I found them in the lang file. Doesn't mean I know what they do :)
I think docs should be written by people who know the subject :)

**Comment by rubensworks** [comment]
Closing due to inactivity.

**Pull request closed without merging**
