### PR TITLE
Let parts expose more than one value

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by josephcsible** [comment]
This should not be merged until #519 is fixed.

**Comment by rubensworks** [comment]
On hold until we have looked into #524.

**Comment by rubensworks** [comment]
@josephcsible I assume this can be merged now, now that #524 is resolved?

**Comment by josephcsible** [comment]
I thought the intent was that #524 would make doing this unnecessary.

**Comment by rubensworks** [comment]
I don't remember what we discussed (I don't think it was here on GitHub, right?). But I think this issue is orthogonal to #524, and doesn't solve the same problem.

**Pull request closed without merging**
