### PR TITLE
Add Rotate operator

### PR DESCRIPTION
**Pull request by bsngardner**
rotates the inputs to an operator, similar to flip

I don't have chinese lang stuff because I don't know chinese. I hope I didn't miss anything; I based it on the flip operator pretty heavily.

### CODE REVIEW

**Comment by rubensworks** [comment]
Thanks! I'll review this in a week or two (on holidays right now)

**Comment by bsngardner** [comment]
I had a thought yesterday: what do you think of making the operator take an integer input to rotate the inputs N times? That way you could get any input to the front with one card. Just a thought; this new operator works to make it possible to reach the later inputs without consuming the first ones.

**Comment by rubensworks** [comment]
> what do you think of making the operator take an integer input to rotate the inputs N times?

That makes sense! Feel free to include it in this PR.

For usability, it might be good to keep the normal `rotate`, and introduce a new `rotate-n` or something like that.

**Comment by josephcsible** [comment]
I don't think I like this. It breaks the idea that f(x, y) is basically equivalent to f(x)(y). It can cause visible differences and strange behavior when used in conjunction with already partially-applied and curried operators, or if an operator returns another operator.

Clarification: my issue with this is that it peeks at the number of operands that the current operator takes. If that value were instead provided to it by the player, or hardcoded to 3, I'd have no problem with this.

**Comment by rubensworks** [comment]
@josephcsible Can you give a concrete example where you feel this will behave strangely?

I don't see any problems with this PR myself atm.

**Comment by bsngardner** [comment]
I commented on Issue #616 about my attempts to follow @josephcsible's explanation on how to rotate operator inputs with the current feature set. If there is a generic way to do it now, cool. I don't actually understand the lambda calculus constraints mentioned, but hopefully we can figure out the best and proper way to have this feature.

**Comment by bsngardner** [comment]
Also, does the flip operator not break the same idea, if I understand what you're saying?

**Review by rubensworks — APPROVED** [review]

**Comment by rubensworks** [comment]
Looks good to merge for me.

@josephcsible Please let me know if you still have issue with this, and if so, please give a concrete example where you feel this will behave strangely

@bsngardner I'm still open to the idea of adding a `rotate-n` as well. Feel free to add it to this PR as well, otherwise I'll merge this PR as-is tomorrow.

**Comment by bsngardner** [comment]
Okay, I'll write a rotate-n this evening

**Comment by josephcsible** [comment]
This kind of fell off my radar. I'm taking another look now to come up with the concrete example.

**Comment by josephcsible** [comment]
Here's one example: Create a list containing the operators Arithmetic Addition and Arithmetic Subtraction. Use "Apply" to apply that list to the "List Get" operator. The result of that is an operator with signature Integer -> Integer -> Integer -> Integer. Passing in 0, 20, and 15 to that operator will return 35, and passing in 1, 20, and 15 will return 5. (Note that if you want to try this, you need to use "apply" followed by "apply2" rather than just using "apply3" to do them all at once, due to bug #352.)

If I rotate that operator, I'd expect that passing 15, 0, and 20 would return 35, and that passing 15, 1, and 20 would return 15. What actually happens is that I get an error: "The operator Rotate received the operator Get with input length 1 while length 2 is required."

**Comment by bsngardner** [comment]
Hmm and this is nontrivial to solve?

**Comment by rubensworks** [comment]
@josephcsible That sounds like a bug, but I don't think the cause lies within this PR. I think the problem might be related to #352 even.

**Comment by josephcsible** [comment]
Okay, here's a better example: imagine instead of `+` and `-`, the list contained `+` and the number 3. Now the arity of the rotated get operator depends on its own inputs in a circular, non-resolvable way.

**Comment by rubensworks** [comment]
Interesting case, I wonder if/how this would crash...

Won't the same problem occur for the flip operator as well?

**Comment by josephcsible** [comment]
No. Flip always just flips the first two operands to an operator, no matter how many there are (with the exception of bug #352). Granted, you'll probably end up trying to apply 3 as if it were an operator, but that's not flip's fault (and choosing a unary operator would make that problem go away too). The problem with this implementation of rotate is that it tries to figure out how many there are and then rotate them all, which can lead to paradoxes. I think the simplest solution is either to make it always assume 3 operands, or have the player pass the number of operands.

**Comment by rubensworks** [comment]
I still don't understand the problem exactly tbh. I should sit down and play with it a bit I guess (but I don't have time for that unfortunately)

@bsngardner Could you have a look to see what happens at runtime when you try out @josephcsible's use cases?

If it indeed fails in some way, we should look into coming up with a different solution, or one of those suggested by @josephcsible.

> I think the simplest solution is either to make it always assume 3 operands, or have the player pass the number of operands.

I don't have a strong opinion on either of them.

**Comment by josephcsible** [comment]
So I thought about this some more, and this isn't a good idea:

> what do you think of making the operator take an integer input to rotate the inputs N times?

Doing this would make it impossible to properly type-check this, since the overall type would be different depending on the values of its inputs, rather than just the types of its inputs.

> have the player pass the number of operands

Ditto.

For evidence of this, consider trying to build the function in Haskell. Rotating three arguments by one place is easy:
```
:t \f x y z -> f y z x
\f x y z -> f y z x :: (t3 -> t2 -> t1 -> t) -> t1 -> t3 -> t2 -> t
```
Even simpler than rotating an arbitrary number of places would be rotating either one or two depending on a Boolean, like this: 
```
:t \b f x y z -> if b then f y z x else f z x y
\b f x y z -> if b then f y z x else f z x y :: Bool -> (t1 -> t1 -> t1 -> t) -> t1 -> t1 -> t1 -> t
```

Note that x, y, and z now all have to be the same type. This isn't true for reduce (or basically any other function in ID), so such an operator would be useless.

**Comment by bsngardner** [comment]
So what operator should we make? rotate-n is unnecessary, so it can be thrown out. I like the idea of passing how many operators should be included in the rotate; it's even more flexible. Are there any problems with this operator? rotate Int -> Op -> Op
I was able to accomplish what I needed this feature for without it using some reordering and meta operators (piping a pipe op to another operator or something, filtering a list and using the length to select an operator in another list, etc; harder but kinda fun). But I still think this would be a useful feature.

**Comment by josephcsible** [comment]
> I like the idea of passing how many operators should be included in the rotate; it's even more flexible.

The problem is that such an operator can never be well-typed. In order for it to be well-typed without requiring all of the inputs to be of the same type (which would break your use case and pretty much every other use case), both the number of operands and the number of places to rotate must be fixed.

There is still a useful Rotate operator to be made, though. It's defined as `rotate f x y z = f y z x`. Just implement that. It's type-safe and works perfectly for your use case.

**Comment by moonheart08** [comment]
Any status on this PR? This operator would be pretty helpful.

**Comment by rubensworks** [comment]
@moonheart08 @bsngardner has been inactive, so feel free to take this PR over if you want.

**Comment by moonheart08** [comment]
@rubensworks I'll consider it. (As in, I'll clone the repo right now, possibly do it, possibly not.)

**Comment by bsngardner** [comment]
I haven't had time to change the rotate to just rotate 3 inputs instead of all of them. I believe that's what was decided. If you have time, it's a small change from what I put in this PR. I just don't have the IDE set up anymore.

**Comment by rubensworks** [comment]
Closing due to inactivity. Feel free to submit a new PR.

**Pull request closed without merging**
