### PR TITLE
[1.16] performance: remove disabling of inventory position when getting ingredient channel slots

### PR DESCRIPTION
**Pull request by Geo25rey**
See discussion: #1152

### CODE REVIEW

**Comment by Geo25rey** [comment]
@rubensworks can you run the CI? I can't get the build config to work locally

**Review by rubensworks — CHANGES_REQUESTED** [review]
I'm afraid these method calls have to remain in-place, because they are needed to handle the case of infinite loops for self-recursive networks (e.g. IT item interfaces are connected to each other directly).
Without them, any call to `getSlots()` on such network will crash the server with a stackoverflow exception.

**Comment by Geo25rey** [comment]
> to handle the case of infinite loops for self-recursive networks

Sounds like this should be a compiled state on block and slot updates. Compiling the state of the network from scratch on every tick seems very wasteful to me. Not sure the best way to go about this since this would likely be a big refactor on your part.

**Comment by Geo25rey** [comment]
> Without them, any call to `getSlots()` on such network will crash the server with a stackoverflow exception.

On the other hand, this could also be a UX issue rather than a technical one. There could be a check when a user updates the network to see if there is any infinite loops possible and prompt the user that doing whatever update they are making will break their network and/or not actually not actually complete the action that the user just made.

**Comment by rubensworks** [comment]
> Sounds like this should be a compiled state on block and slot updates. Compiling the state of the network from scratch on every tick seems very wasteful to me. Not sure the best way to go about this since this would likely be a big refactor on your part.

The state _is_ precompiled. Recalculation only happens when placing new cables.

**Comment by rubensworks** [comment]
> On the other hand, this could also be a UX issue rather than a technical one. There could be a check when a user updates the network to see if there is any infinite loops possible and prompt the user that doing whatever update they are making will break their network and/or not actually not actually complete the action that the user just made.

Yes, something like this may indeed be better. But this might not be that easy to achieve though, since loops could also be achieved with hops through other networks (even from other mods). But I'm definitely open to improvements in this regard.

Related to https://github.com/CyclopsMC/IntegratedTunnels/issues/69

**Comment by rubensworks** [comment]
Closing due to inactivity.

**Pull request closed without merging**
